import {
  Accessibility,
  Archive,
  Bath,
  Bike,
  Car,
  CheckCircle,
  Coffee,
  Dumbbell,
  Fan,
  Flame,
  Gamepad2,
  Lock,
  Microwave,
  Mic,
  Piano,
  PlugZap,
  Sandwich,
  Sun,
  Trees,
  Tv,
  Waves,
  Wifi,
  Wind,
  Zap
} from 'lucide-react';

export const AMENITIES_LIST = [
  { id: 'Accessibilité PMR', icon: <Accessibility size={20} /> },
  { id: 'Appareil de sport', icon: <Dumbbell size={20} /> },
  { id: 'Baignoire', icon: <Bath size={20} /> },
  { id: 'Balcon / terrasse / jardin', icon: <Trees size={20} /> },
  { id: 'Barbecue', icon: <Flame size={20} /> },
  { id: 'Blender', icon: <CheckCircle size={20} /> },
  { id: 'Bouilloire', icon: <Coffee size={20} /> },
  { id: 'Cafetière', icon: <Coffee size={20} /> },
  { id: 'Cheminée', icon: <Flame size={20} /> },
  { id: 'Climatisation', icon: <Wind size={20} /> },
  { id: 'Console de jeu', icon: <Gamepad2 size={20} /> },
  { id: 'Digicode', icon: <Lock size={20} /> },
  { id: 'Fer à repasser', icon: <Zap size={20} /> },
  { id: 'Four', icon: <Sun size={20} /> },
  { id: 'Grille-pain', icon: <Sandwich size={20} /> },
  { id: 'Interphone', icon: <Mic size={20} /> },
  { id: 'Lave-linge', icon: <Wind size={20} /> },
  { id: 'Lave-vaisselle', icon: <Waves size={20} /> },
  { id: 'Local vélo', icon: <Bike size={20} /> },
  { id: 'Micro-ondes', icon: <Microwave size={20} /> },
  { id: 'Parking', icon: <Car size={20} /> },
  { id: 'Piano', icon: <Piano size={20} /> },
  { id: 'Piscine', icon: <Waves size={20} /> },
  { id: 'Rangements indépendants', icon: <Archive size={20} /> },
  { id: 'Recharge véhicule électrique', icon: <PlugZap size={20} /> },
  { id: 'Sèche-cheveux', icon: <Wind size={20} /> },
  { id: 'Sèche-linge', icon: <Sun size={20} /> },
  { id: 'Télévision', icon: <Tv size={20} /> },
  { id: 'Ventilateur', icon: <Fan size={20} /> },
  { id: 'Wifi Fibre', icon: <Wifi size={20} /> },
] as const;
